import { Badge } from "@/components/ui/badge";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DUbGf7XaQ8i
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Hero() {
  return (
    <div className="w-full h-screen flex flex-col justify-center items-center bg-gray-100 text-center px-4 md:px-6">
      <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-gray-900 mb-6 md:mb-8">
        OneLnk
      </h1>
      <p className="max-w-2xl text-lg sm:text-xl md:text-2xl text-gray-700 mb-6 md:mb-8 mx-auto">
        Crie sua página de links agora mesmo!
      </p>
      <div className="flex flex-wrap justify-center gap-4">
        <Button size="lg" className="text-base" asChild>
          <Link href="/pages">Criar página</Link>
        </Button>
      </div>
    </div>
  );
}
