import { Card, CardContent } from "@/components/ui/card";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/329ptpXyots
 */
import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { sql } from "@vercel/postgres";

export async function LinkList({ pageId }: { pageId: string }) {
  const { rows } =
    await sql`SELECT * FROM public."links" WHERE page_id = ${pageId}`;

  return (
    <div className="flex flex-col w-full">
      {rows.map((link) => (
        <Card key={link.id} className="w-full max-w-md mb-4">
          <CardContent className="p-4">
            <Button className="w-full" variant="ghost">
              <Link
                className="w-full text-center"
                target="_blank"
                href={link.url}
              >
                {link.name}
              </Link>
            </Button>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
