import { Card, CardContent } from "@/components/ui/card";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/329ptpXyots
 */
import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function LinkList({ slug }: { slug: string }) {
  return (
    <div className="flex flex-col items-center p-4 md:p-8">
      <Avatar className="w-24 h-24 rounded-full mb-4" />
      <h1 className="text-2xl font-semibold mb-4">John Doe</h1>
      <p className="text-center text-gray-600 mb-8">
        Welcome to my link aggregator. Click on any link to learn more about me
        or to check out my work.
      </p>
      <Card className="w-full max-w-md mb-4">
        <CardContent className="p-4">
          <Button className="w-full" variant="ghost">
            <Link className="w-full text-center" href="#">
              GitHub
            </Link>
          </Button>
        </CardContent>
      </Card>
      <Card className="w-full max-w-md mb-4">
        <CardContent className="p-4">
          <Button className="w-full" variant="ghost">
            <Link className="w-full text-center" href="#">
              Twitter
            </Link>
          </Button>
        </CardContent>
      </Card>
      <Card className="w-full max-w-md mb-4">
        <CardContent className="p-4">
          <Button className="w-full" variant="ghost">
            <Link className="w-full text-center" href="#">
              LinkedIn
            </Link>
          </Button>
        </CardContent>
      </Card>
      <Card className="w-full max-w-md mb-4">
        <CardContent className="p-4">
          <Button className="w-full" variant="ghost">
            <Link className="w-full text-center" href="#">
              Blog
            </Link>
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
